Algoritmo "Aula 7"

Var
nome : caractere
Produtos : vetor [1..5] de caractere
numeros : vetor [1..3] de inteiro
i : inteiro


Inicio
nome <- "Mariano"

produtos [1] <- "Banana"
produtos [3] <- "Salgadinho"
produtos [4] <- "Refrigerante"
produtos [5] <- "Café"

//enquanto (condicao)
//contador <= contador + 1
para i <- 1 ate 3 faca
     leia(numeros[i])
fimPara

para i <- 1 ate 3 faca
     escreval("n ",i,"°",numeros[i])
fimPara


Fimalgoritmo