Algoritmo "Aula1"

Var
// Seção de Declarações das variáveis
// TIPOS DE DADOS
// caractere - texto
nome : caractere
// real - decimal, numero quebrados
valor : real
// inteiro - "valor redondo"
idade : inteiro
// logico - verdadeiro e falso. boolean
ligado : logico

// regras de variáveis
// 1 - não pode palvras dedicadas
// 2 - não pode caractere especial, só em print/escreva
// 3 - não pode acentos e cedilha, só em print/escreva
// 4 - não pode começar com número, só com número
// 5 - mão pode espaços vazios
//     *camel case - nomeComposto
//     *snake case - nome_composto
//     *upper case - NOMECOMPOSTO (maiusculo)
//     *lower case - nomecomposto (minusculo)


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval ("Hello World")
escreval ("Mariano massa demais")
escreval (3+1234567824)
Fimalgoritmo